# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SeleniumrViewer(object):
    def setupUi(self, SeleniumrViewer):
        num = int(200/4)*480 #200 luồng 4 hàng và y=480
        print(num)
        SeleniumrViewer.setObjectName("SeleniumrViewer")
        SeleniumrViewer.resize(2000-100, 754)
        # SeleniumrViewer.setMinimumSize(QtCore.QSize(2000-100, 0))
        SeleniumrViewer.setMaximumSize(QtCore.QSize(2000-100, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(SeleniumrViewer)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(SeleniumrViewer)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 2018, num))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(2000, num))
        self.frame.setMaximumSize(QtCore.QSize(200, num))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.hwnd = {}
        index = index1 = 0
        index2 = 1
        for i in range(200):
            if i == 4*index2:
                index = 0
                index1 += 1
                index2 += 1
            self.label = QtWidgets.QLabel(self.frame)
            self.label.setGeometry(QtCore.QRect(465*index, 480*index1, 460, 475))
            self.label.setMinimumSize(QtCore.QSize(460, 475))
            self.label.setMaximumSize(QtCore.QSize(460, 475))
            # self.label.setStyleSheet("background-color: rgb(85, 255, 0);")
            self.hwnd[i] = int(self.label.winId())
            index += 1
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(SeleniumrViewer)
        QtCore.QMetaObject.connectSlotsByName(SeleniumrViewer)

    def retranslateUi(self, SeleniumrViewer):
        _translate = QtCore.QCoreApplication.translate
        SeleniumrViewer.setWindowTitle(_translate("SeleniumrViewer", "SeleniumrViewer"))


